---
# create meta dirtectory
- name: mkdir for metadir
  become: yes
  file:
    path: '{{ starrocks_meta_dir }}'
    state: directory
    owner: starrocks
    group: starrocks
    mode: 0755
  tags: config

- name: alter fe metadir
  become: yes
  become_user: starrocks
  lineinfile:
    path: '{{ starrocks_fe_conf_path }}'
    insertafter: '# store metadata'
    line: 'meta_dir = {{ starrocks_meta_dir }}'
  tags: config

- name: append java home
  become: yes
  become_user: starrocks
  lineinfile:
    path: '{{ starrocks_fe_conf_path }}'
    line: 'JAVA_HOME = {{ starrocks_java_home }}'
  tags: config

# create storage dirtectory
- name: mkdir for storage
  become: yes
  file:
    path: '{{ starrocks_storage_dir }}'
    state: directory
    owner: starrocks
    group: starrocks
    mode: 0755
  tags: config

- name: alter be storage dir
  become: yes
  become_user: starrocks
  lineinfile:
    path: '{{ starrocks_be_conf_path }}'
    insertafter: '# storage_root_path = ${STARROCKS_HOME}/storage'
    line: "storage_root_path = {{ starrocks_storage_dir }}"
  tags: config
