---
- name: alter fe metadir
  lineinfile:
    dest: '{{ starrocks_fe_conf_path }}'
    insertafter: '# store metadata'
    line: 'meta_dir = {{ starrocks_meta_dir }}\n'

- name: alter be storage dir
  lineinfile:
    desc: '{{ starrocks_be_conf_path }}'
    insertafter: '# storage_root_path'
    line: "storage_root_path = {{ starrocks_storage_dir }}\n"
