---
# register fe.id and be.id file
- name: checking if fe.pid file exists
  become: yes
  become_user: starrocks
  stat:
    path: '{{ starrocks_home }}/fe/bin/fe.pid'
  register: fe_pid
  tags:
    - start
    - stop
    - start_fe
    - stop_fe

- name: checking if be.pid file exists
  become: yes
  become_user: starrocks
  stat:
    path: '{{ starrocks_home }}/be/bin/be.pid'
  register: be_pid
  tags:
    - start
    - stop
    - start_be
    - stop_be

- name: checking if apache_hdfs_broker.pid file exists
  become: yes
  become_user: starrocks
  stat:
    path: '{{ starrocks_home }}/apache_hdfs_broker/bin/apache_hdfs_broker.pid'
  register: broker_pid
  tags:
    - start
    - stop
    - start_broker
    - stop_broker

# register if mysql is alive
- name: checking if mysql is alive
  become: yes
  become_user: starrocks
  shell:
    cmd: ' mysql -h{{ groups["cluster1.master"][0] }} -P9030 -uroot -e "show databases;"'
  register: mysqlstatus
  failed_when: mysqlstatus.rc == 2
  tags:
    - role
    - role_be
    - role_broker
