---
# check master is start
- name: Wait starrocks master is start and running
  become: yes
  become_user: starrocks
  wait_for:
    path: "{{ starrocks_home }}/fe/log/fe.log"
    search_regex: ".*Open mysql server success on 9030.*"
  when: ansible_ssh_host in groups["dorisdb_master"]
  tags:
    - role

- name: add follower
  become: yes
  become_user: starrocks
  shell:
    cmd: echo "ALTER SYSTEM ADD FOLLOWER \"{{ ansible_ssh_host }}:9010\";" | mysql -h{{ groups["dorisdb_master"][0] }} -P9030 -uroot
  when: ansible_ssh_host in groups["dorisdb_follower"]
  tags:
    - role
    - role_fe
    - role_fe_follower

# - name: add observer
#   become: yes
#   become_user: starrocks
#   shell:
#     cmd: echo "ALTER SYSTEM ADD OBSERVER \"{{ item }}:9010\";" | mysql -h{{ groups["dorisdb_master"][0] }} -P9030 -uroot
#   with_items: '{{ groups["dorisdb_observer"] }}'
#   tags: roles

# add all backends in mysql
- name: add backend
  become: yes
  become_user: starrocks
  shell:
    cmd: echo "ALTER SYSTEM ADD BACKEND \"{{ ansible_ssh_host }}:9050\";" | mysql -h{{ groups["dorisdb_master"][0] }} -P9030 -uroot
  when: ansible_ssh_host in groups["dorisdb_backends"]
  tags:
    - role
    - role_be

# add all brokers in mysql
- name: add broker
  become: yes
  become_user: starrocks
  shell:
    cmd: echo "ALTER SYSTEM ADD BROKER broker1 \"{{ ansible_ssh_host }}:8000\";" | mysql -h{{ groups["dorisdb_master"][0] }} -P9030 -uroot
  when: ansible_ssh_host in groups["dorisdb_brokers"]
  tags:
    - role
    - role_broker
