---
- name: add backend
  become: yes
  become_user: starrocks
  shell:
    cmd: echo "ALTER SYSTEM ADD BACKEND \"{{ item }}:9050\";" | mysql -h{{ groups["cluster1.master"][0] }} -P9030 -uroot
  with_items: '{{ groups["cluster1.backends"] }}'
  tags:
    - roles
    - be

# - name: add follower
#   become: yes
#   become_user: starrocks
#   shell:
#     cmd: echo "ALTER SYSTEM ADD FOLLOWER \"{{ item }}:9010\";" | mysql -h{{ groups["cluster1.master"][0] }} -P9030 -uroot
#   with_items: '{{ groups["cluster1.follower"] }}'
#   tags: roles
#
# - name: add observer
#   become: yes
#   become_user: starrocks
#   shell:
#     cmd: echo "ALTER SYSTEM ADD OBSERVER \"{{ item }}:9010\";" | mysql -h{{ groups["cluster1.master"][0] }} -P9030 -uroot
#   with_items: '{{ groups["cluster1.observer"] }}'
#   tags: roles


- name: add broker
  become: yes
  become_user: starrocks
  shell:
    cmd: echo "ALTER SYSTEM ADD BROKER broker1 \"{{ item }}:8000\";" | mysql -h{{ groups["cluster1.master"][0] }} -P9030 -uroot
  with_items: '{{ groups["cluster1.brokers"] }}'
  tags:
    - roles
    - broker
