---
# start fe in master
- name: start fe master
  become: yes
  become_user: starrocks
  shell:
    cmd: "cd {{ starrocks_home }}/fe && bin/start_fe.sh --daemon"
  when: (ansible_ssh_host in groups["cluster1.master"] and not fe_pid.stat.exists)
  tags:
    - start
    - start_fe

# start be in all
- name: start be
  become: yes
  become_user: starrocks
  shell:
    cmd: "cd {{ starrocks_home }}/be && bin/start_be.sh --daemon"
  when: (ansible_ssh_host in groups["cluster1.backends"] and not be_pid.stat.exists)
  tags:
    - start
    - start_be

# start broker in all
# ATTENTION: export JAVA_HOME variable before execute start_broker.sh
- name: start broker
  become: yes
  become_user: starrocks
  shell:
    cmd: "export JAVA_HOME={{ starrocks_java_home }}; cd {{ starrocks_home }}/apache_hdfs_broker && bin/start_broker.sh --daemon"
  when: (ansible_ssh_host in groups["cluster1.brokers"] and not broker_pid.stat.exists)
  tags:
    - start
    - start_broker
