---
- name: start fe master
  become: yes
  become_user: starrocks
  shell:
    cmd: "cd {{ starrocks_home }}/fe && bin/start_fe.sh --daemon"
  tags: start

# - name: start be
#   shell:
#     cmd: "sh {{ starrocks_home }}/be/bin/start_be.sh --daemon"
