---
# create new group first.
- name: create group
  become: yes
  become_user: root
  group: name=starrocks state=present
# then create user in the same group
- name: create user
  become: yes
  become_user: root
  user: name=starrocks group=starrocks shell=/bin/bash
